[package]
name = "rinstall"
version = "0.3.0"
edition = "2021"
license = "GPL-3.0+"
authors = ["Danilo Spinella <danilo.spinella@suse.com>"]
keywords = ["packaging"]
repository = "https://github.com/danyspin97/rinstall"
homepage = "https://github.com/danyspin97/rinstall"
description = "Declarative install for programs"
categories = ["command-line-utilities"]

[dependencies]
blake3 = "1.3.1"
camino = { version = "1.1.1", features = [ "serde1" ] }
clap = { version = "4.0.9", features = ["derive", "env", "wrap_help", "help", "usage", "error-context"] }
color-eyre = { version = "0.6.2", default_features = false }
colored = "2.0.0"
json = "0.12.4"
lazy_static = "1.4.0"
libc = "0.2.134"
log = { version = "0.4.17", features = [ "std" ] }
semver = { version = "1.0.14", features = ["serde"] }
serde = { version = "1.0.145", features = ["derive"] }
serde_yaml = "0.9.13"
xdg = "2.4.1"
walkdir = "2.3.2"
void = "1.0.2"

[build-dependencies]
clap = { version = "4.0.9", features = ["derive", "cargo", "env"] }
clap_complete = "4.0.2"
clap_mangen = "0.2.2"
# used for the imports in src/config.rs
serde = { version = "1.0.145", features = ["derive"] }
